# Install by running
#   pre-commit install -t pre-commit -t pre-push -t prepare-commit-msg
default_stages: [commit, push]
repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.5.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
    additional_dependencies:
    - "@commitlint/config-conventional"
    - conventional-changelog-conventionalcommits

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-executables-have-shebangs
  - id: check-json
    exclude: "vscode/(keybindings|settings)\\.json$"
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: detect-private-key
  - id: end-of-file-fixer

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
  - id: detect-secrets
    args:
    - "--baseline"
    - ".secrets.baseline"
